[window]
padding.x = 8
padding.y = 8

[font]
normal.family = "CaskaydiaMono Nerd Font"
bold.family = "CaskaydiaMono Nerd Font"
italic.family = "CaskaydiaMono Nerd Font"

size = 14.0

[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
