# Catppuccino Mocha Colors

# Background colors
background = #1e1e2e
background_alt = #181825
background_inactive = #11111b

# Text colors
text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de

# Block colors
block_background = #313244
block_separator = #45475a
block_separator_line = #585b70

# Highlight colors
highlight0 = #6c7086
highlight1 = #7f849c
highlight2 = #9399b2

# Extra colors (customize as needed)
blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc

# Transparent color (if needed)
transparent = #FF00000

